import assert from 'node:assert/strict';

import { Given, Then, When } from '@cucumber/cucumber';

import { GatewayWorld, config, unique } from '../support/world';

function expand(world: GatewayWorld, text: string): string {
  return world.expand(text);
}

// ---------------------------------------------------------------- credentials

Given('I use the master key', function (this: GatewayWorld) {
  this.credential = config.masterKey;
});

Given('a virtual key with no limits', async function (this: GatewayWorld) {
  const key = await this.createKey();
  this.credential = key.secret;
  this.vars.keyId = key.id;
});

Given('a virtual key allowed only {string}', async function (this: GatewayWorld, model: string) {
  const key = await this.createKey({ allowed_models: [model] });
  this.credential = key.secret;
  this.vars.keyId = key.id;
});

Given('a virtual key limited to {int} requests per minute', async function (this: GatewayWorld, rpm: number) {
  const key = await this.createKey({ rpm_limit: rpm });
  this.credential = key.secret;
  this.vars.keyId = key.id;
});

Given('a virtual key with a budget of {float} USD', async function (this: GatewayWorld, budget: number) {
  const key = await this.createKey({ max_budget_usd: budget });
  this.credential = key.secret;
  this.vars.keyId = key.id;
});

Given('I am signed in to the API as a viewer', async function (this: GatewayWorld) {
  this.credential = (await this.createConsoleUser('viewer')).token;
});

When('the key is deleted by an admin', async function (this: GatewayWorld) {
  const res = await this.admin('DELETE', `/keys/${this.vars.keyId}`);
  assert.equal(res.status, 200, res.text);
});

When('the key is regenerated by an admin', async function (this: GatewayWorld) {
  const res = await this.admin('POST', `/keys/${this.vars.keyId}/regenerate`);
  assert.equal(res.status, 200, res.text);
  this.vars.regenerated = res.json.key;
});

When('I use the regenerated key', function (this: GatewayWorld) {
  this.credential = this.vars.regenerated;
});

// ---------------------------------------------------------------- chat

When(
  'I send a chat request for model {string} saying {string}',
  async function (this: GatewayWorld, model: string, text: string) {
    await this.chat(expand(this, text), {}, model);
  },
);

When(
  'I send a chat request for model {string} saying {string} with routing strategy {string}',
  async function (this: GatewayWorld, model: string, text: string, strategy: string) {
    await this.chat(expand(this, text), { routing_strategy: strategy, no_cache: true }, model);
  },
);

When('I send {int} chat requests for model {string}', async function (this: GatewayWorld, n: number, model: string) {
  for (let i = 0; i < n; i += 1) {
    const res = await this.chat(`request ${i} ${unique('n')}`, {}, model);
    assert.equal(res.status, 200, res.text);
  }
});

When('I send a chat request without credentials', async function (this: GatewayWorld) {
  await this.request('POST', '/v1/chat/completions', {
    body: { model: 'eval-chat', messages: [{ role: 'user', content: 'hi' }] },
  });
});

When('I send a deterministic chat request saying {string}', async function (this: GatewayWorld, text: string) {
  await this.chat(expand(this, text), { temperature: 0 });
});

When(
  'I send a deterministic chat request saying {string} with caching disabled',
  async function (this: GatewayWorld, text: string) {
    await this.chat(expand(this, text), { temperature: 0, no_cache: true });
  },
);

When(
  'I stream a chat request for model {string} saying {string}',
  async function (this: GatewayWorld, model: string, text: string) {
    const res = await this.request('POST', '/v1/chat/completions', {
      token: this.credential,
      body: { model, stream: true, messages: [{ role: 'user', content: expand(this, text) }] },
    });
    assert.equal(res.status, 200, res.text);
    assert.match(res.text, /data: \[DONE\]/);
  },
);

// ---------------------------------------------------------------- assertions

Then('the response status is {int}', function (this: GatewayWorld, status: number) {
  assert.ok(this.response, 'no request was made');
  assert.equal(this.response.status, status, this.response.text);
});

Then('the error code is {string}', function (this: GatewayWorld, code: string) {
  assert.equal(this.response?.json?.error?.code, code, this.response?.text ?? "no response");
});

Then('the response header {string} is {string}', function (this: GatewayWorld, name: string, value: string) {
  assert.equal(this.response?.headers.get(name), value, `${name} header; body: ${this.response?.text}`);
});

Then('the response has a {string} header', function (this: GatewayWorld, name: string) {
  assert.ok(this.response?.headers.get(name), `missing ${name} header`);
});

Then('the reply is {string}', function (this: GatewayWorld, text: string) {
  assert.equal(this.response?.json?.choices?.[0]?.message?.content, text);
});

Then('the reply contains {string}', function (this: GatewayWorld, text: string) {
  const content: string = this.response?.json?.choices?.[0]?.message?.content ?? '';
  assert.ok(content.includes(text), `expected ${JSON.stringify(content)} to contain ${text}`);
});

Then('the reply does not contain {string}', function (this: GatewayWorld, text: string) {
  const content: string = this.response?.json?.choices?.[0]?.message?.content ?? '';
  assert.ok(!content.includes(text), `expected ${JSON.stringify(content)} not to contain ${text}`);
});

Then('the streamed text is {string}', function (this: GatewayWorld, text: string) {
  assert.equal(this.streamed.trim(), text);
});
