"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 16:26:28.939058
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_email"), "admin_users", ["email"], unique=True)
    op.create_table(
        "guardrail_violations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("virtual_key_id", sa.String(length=36), nullable=True),
        sa.Column("policy", sa.String(length=100), nullable=False),
        sa.Column("rule", sa.String(length=255), nullable=False),
        sa.Column("phase", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("match_count", sa.Integer(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_guardrail_violations_created", "guardrail_violations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_guardrail_violations_request_id"),
        "guardrail_violations",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guardrail_violations_virtual_key_id"),
        "guardrail_violations",
        ["virtual_key_id"],
        unique=False,
    )
    op.create_table(
        "mcp_servers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("command", sa.String(length=1024), nullable=True),
        sa.Column(
            "args",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "env",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column(
            "headers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "discovered_tools",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("tool_prefix", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mcp_servers_name"), "mcp_servers", ["name"], unique=True)
    op.create_table(
        "rag_collections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_dimensions", sa.Integer(), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rag_collections_name"), "rag_collections", ["name"], unique=True)
    op.create_table(
        "request_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("virtual_key_id", sa.String(length=36), nullable=True),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("end_user", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("resolved_model", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("deployment_id", sa.String(length=255), nullable=True),
        sa.Column("route", sa.String(length=128), nullable=True),
        sa.Column("dialect", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("time_to_first_token_ms", sa.Float(), nullable=True),
        sa.Column(
            "stage_timings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("routing_strategy", sa.String(length=64), nullable=True),
        sa.Column("routing_reason", sa.Text(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("cache_similarity", sa.Float(), nullable=True),
        sa.Column("guardrail_flagged", sa.Boolean(), nullable=False),
        sa.Column(
            "guardrail_results",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column("tool_calls_count", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "request_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "response_body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_logs_cache_hit"), "request_logs", ["cache_hit"], unique=False)
    op.create_index(
        op.f("ix_request_logs_created_at"), "request_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_request_logs_created_key",
        "request_logs",
        ["created_at", "virtual_key_id"],
        unique=False,
    )
    op.create_index(
        "ix_request_logs_created_model", "request_logs", ["created_at", "model"], unique=False
    )
    op.create_index(op.f("ix_request_logs_provider"), "request_logs", ["provider"], unique=False)
    op.create_index(
        op.f("ix_request_logs_request_id"), "request_logs", ["request_id"], unique=False
    )
    op.create_index("ix_request_logs_status", "request_logs", ["status"], unique=False)
    op.create_index(op.f("ix_request_logs_team_id"), "request_logs", ["team_id"], unique=False)
    op.create_index(op.f("ix_request_logs_trace_id"), "request_logs", ["trace_id"], unique=False)
    op.create_index(
        op.f("ix_request_logs_virtual_key_id"), "request_logs", ["virtual_key_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("max_budget_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("spend_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("budget_period", sa.String(length=20), nullable=False),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "usage_rollups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("virtual_key_id", sa.String(length=36), nullable=True),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("cache_hit_count", sa.Integer(), nullable=False),
        sa.Column("fallback_count", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cost_saved_usd", sa.Float(), nullable=False),
        sa.Column("total_latency_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bucket", "virtual_key_id", "model", "provider", name="uq_usage_rollup_bucket"
        ),
    )
    op.create_index("ix_usage_rollups_bucket", "usage_rollups", ["bucket"], unique=False)
    op.create_index(op.f("ix_usage_rollups_team_id"), "usage_rollups", ["team_id"], unique=False)
    op.create_index(
        op.f("ix_usage_rollups_virtual_key_id"), "usage_rollups", ["virtual_key_id"], unique=False
    )
    op.create_table(
        "rag_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=1024), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["collection_id"], ["rag_collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rag_documents_collection_id"), "rag_documents", ["collection_id"], unique=False
    )
    op.create_index(
        op.f("ix_rag_documents_content_hash"), "rag_documents", ["content_hash"], unique=False
    )
    op.create_table(
        "virtual_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=24), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=True),
        sa.Column("max_budget_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("spend_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("budget_period", sa.String(length=20), nullable=False),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rpm_limit", sa.Integer(), nullable=True),
        sa.Column("tpm_limit", sa.Integer(), nullable=True),
        sa.Column("max_parallel_requests", sa.Integer(), nullable=True),
        sa.Column(
            "allowed_models",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "blocked_models",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("guardrail_policy", sa.String(length=100), nullable=True),
        sa.Column(
            "allowed_routes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_virtual_keys_key_hash"), "virtual_keys", ["key_hash"], unique=True)
    op.create_table(
        "rag_chunks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("vector_id", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["rag_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_rag_chunk_position"),
    )
    op.create_index(
        op.f("ix_rag_chunks_collection_id"), "rag_chunks", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_rag_chunks_document_id"), "rag_chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_rag_chunks_vector_id"), "rag_chunks", ["vector_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_chunks_vector_id"), table_name="rag_chunks")
    op.drop_index(op.f("ix_rag_chunks_document_id"), table_name="rag_chunks")
    op.drop_index(op.f("ix_rag_chunks_collection_id"), table_name="rag_chunks")
    op.drop_table("rag_chunks")
    op.drop_index(op.f("ix_virtual_keys_key_hash"), table_name="virtual_keys")
    op.drop_table("virtual_keys")
    op.drop_index(op.f("ix_rag_documents_content_hash"), table_name="rag_documents")
    op.drop_index(op.f("ix_rag_documents_collection_id"), table_name="rag_documents")
    op.drop_table("rag_documents")
    op.drop_index(op.f("ix_usage_rollups_virtual_key_id"), table_name="usage_rollups")
    op.drop_index(op.f("ix_usage_rollups_team_id"), table_name="usage_rollups")
    op.drop_index("ix_usage_rollups_bucket", table_name="usage_rollups")
    op.drop_table("usage_rollups")
    op.drop_table("teams")
    op.drop_index(op.f("ix_request_logs_virtual_key_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_trace_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_team_id"), table_name="request_logs")
    op.drop_index("ix_request_logs_status", table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_request_id"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_provider"), table_name="request_logs")
    op.drop_index("ix_request_logs_created_model", table_name="request_logs")
    op.drop_index("ix_request_logs_created_key", table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_created_at"), table_name="request_logs")
    op.drop_index(op.f("ix_request_logs_cache_hit"), table_name="request_logs")
    op.drop_table("request_logs")
    op.drop_index(op.f("ix_rag_collections_name"), table_name="rag_collections")
    op.drop_table("rag_collections")
    op.drop_index(op.f("ix_mcp_servers_name"), table_name="mcp_servers")
    op.drop_table("mcp_servers")
    op.drop_index(op.f("ix_guardrail_violations_virtual_key_id"), table_name="guardrail_violations")
    op.drop_index(op.f("ix_guardrail_violations_request_id"), table_name="guardrail_violations")
    op.drop_index("ix_guardrail_violations_created", table_name="guardrail_violations")
    op.drop_table("guardrail_violations")
    op.drop_index(op.f("ix_admin_users_email"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
