@api
Feature: Virtual keys, quotas, and budgets
  Operators hand applications scoped keys instead of provider credentials.

  Scenario: A key only reaches the models it is allowed
    Given a virtual key allowed only "eval-router"
    When I send a chat request for model "eval-chat" saying "hi"
    Then the response status is 403
    And the error code is "permission_denied"
    When I send a chat request for model "eval-router" saying "hi"
    Then the response status is 200

  Scenario: A key's request rate is limited
    Given a virtual key limited to 2 requests per minute
    When I send 2 chat requests for model "eval-chat"
    And I send a chat request for model "eval-chat" saying "one too many"
    Then the response status is 429
    And the error code is "rate_limit_exceeded"
    And the response has a "Retry-After" header

  Scenario: A key's budget is enforced
    Given a virtual key with a budget of 0.000001 USD
    When I send a chat request for model "eval-chat" saying "spend it"
    Then the response status is 200
    When I send a chat request for model "eval-chat" saying "over budget"
    Then the response status is 402
    And the error code is "budget_exceeded"

  Scenario: A deleted key stops working immediately
    Given a virtual key with no limits
    When the key is deleted by an admin
    And I send a chat request for model "eval-chat" saying "hi"
    Then the response status is 401

  Scenario: A regenerated key replaces the old secret
    Given a virtual key with no limits
    When the key is regenerated by an admin
    And I send a chat request for model "eval-chat" saying "hi"
    Then the response status is 401
    When I use the regenerated key
    And I send a chat request for model "eval-chat" saying "hi"
    Then the response status is 200
