import { useMemo, useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import DeleteOutlineRounded from '@mui/icons-material/DeleteOutlineRounded';
import EditRounded from '@mui/icons-material/EditRounded';
import AddRounded from '@mui/icons-material/AddRounded';
import AutorenewRounded from '@mui/icons-material/AutorenewRounded';
import { DataTable, EmptyState, ErrorState, PageHeader, LoadingState, ConfirmDialog, CopyButton } from '../components/Shared';
import { useAuth } from '../auth/AuthProvider';
import { useKeys } from '../api/hooks/useKeys';
import { useAdminModels } from '../api/hooks/useModelsAdmin';
import { useTeams } from '../api/hooks/useTeams';
import { useCreateKey, useDeleteKey, useRegenerateKey, useUpdateKey } from '../api/hooks/useKeysAdmin';
import { BudgetBar, formatDate, useAdminMutationFeedback } from '../features/admin/AdminPrimitives';
import type { KeyCreateRequest, KeyUpdateRequest, VirtualKey } from '../api/types';
import type { GridColDef } from '@mui/x-data-grid';

const emptyForm: KeyCreateRequest = { name: '', team_id: null, allowed_models: [], max_budget_usd: null, budget_duration: 'monthly', rpm_limit: null, tpm_limit: null, expires_at: null };
export default function Keys() { const { user } = useAuth(); const canMutate = user?.role === 'admin'; const [page, setPage] = useState(0); const [createOpen, setCreateOpen] = useState(false); const [form, setForm] = useState<KeyCreateRequest>(emptyForm); const [edit, setEdit] = useState<VirtualKey | null>(null); const [confirm, setConfirm] = useState<{ kind: 'delete' | 'regenerate'; key: VirtualKey } | null>(null); const [plaintext, setPlaintext] = useState<string | null>(null); const keys = useKeys(25, page * 25); const models = useAdminModels(); const teams = useTeams(); const create = useCreateKey(); const update = useUpdateKey(); const regenerate = useRegenerateKey(); const remove = useDeleteKey(); const feedback = useAdminMutationFeedback();
  const teamName = useMemo(() => new Map((teams.data?.items ?? []).map((team) => [team.id, team.name])), [teams.data]);
  const submitCreate = () => { create.mutate(form, { onSuccess: (key) => { setCreateOpen(false); setForm(emptyForm); setPlaintext(key.key ?? null); feedback.notify('Virtual key created.'); }, onError: feedback.fail }); };
  const submitEdit = () => { if (!edit) return; const body: KeyUpdateRequest = { name: edit.name, max_budget_usd: edit.max_budget_usd, budget_duration: edit.budget_duration, rpm_limit: edit.rpm_limit, tpm_limit: edit.tpm_limit, allowed_models: edit.allowed_models, expires_at: edit.expires_at, enabled: edit.enabled }; update.mutate({ id: edit.id, body }, { onSuccess: () => { setEdit(null); feedback.notify('Key limits updated.'); }, onError: feedback.fail }); };
  const runConfirm = () => { if (!confirm) return; if (confirm.kind === 'delete') { remove.mutate(confirm.key.id, { onSuccess: () => { setConfirm(null); feedback.notify('Key deleted.'); }, onError: feedback.fail }); } else { regenerate.mutate(confirm.key.id, { onSuccess: (key) => { setConfirm(null); setPlaintext(key.key ?? null); feedback.notify('Key regenerated.'); }, onError: feedback.fail }); } };
  const columns: GridColDef<VirtualKey>[] = [{ field: 'name', headerName: 'Name', flex: 1, minWidth: 160 }, { field: 'key_prefix', headerName: 'Key prefix', width: 130 }, { field: 'team_id', headerName: 'Team', width: 130, valueGetter: (_, row) => row.team_id ? teamName.get(row.team_id) ?? row.team_id : '—' }, { field: 'allowed_models', headerName: 'Models allowed', flex: 1, minWidth: 160, valueGetter: (_, row) => row.allowed_models.length ? row.allowed_models.join(', ') : 'All models' }, { field: 'budget', headerName: 'Budget / spend', minWidth: 180, flex: 1, renderCell: ({ row }) => <BudgetBar spent={row.spend_usd} budget={row.max_budget_usd} /> }, { field: 'limits', headerName: 'RPM / TPM', width: 120, valueGetter: (_, row) => `${row.rpm_limit ?? '∞'} / ${row.tpm_limit ?? '∞'}` }, { field: 'status', headerName: 'Status', width: 105, renderCell: ({ row }) => row.enabled ? 'Active' : 'Disabled' }, { field: 'created_at', headerName: 'Created', width: 160, valueGetter: (_, row) => formatDate(row.created_at) }, { field: 'last_used_at', headerName: 'Last used', width: 160, valueGetter: (_, row) => formatDate(row.last_used_at) }, { field: 'actions', headerName: 'Actions', width: 180, sortable: false, renderCell: ({ row }) => canMutate ? <Stack direction="row"><IconButton aria-label="Edit key limits" onClick={() => setEdit(row)}><EditRounded fontSize="small" /></IconButton><IconButton aria-label="Regenerate key" onClick={() => setConfirm({ kind: 'regenerate', key: row })}><AutorenewRounded fontSize="small" /></IconButton><IconButton aria-label={row.enabled ? 'Disable key' : 'Enable key'} onClick={() => update.mutate({ id: row.id, body: { enabled: !row.enabled } }, { onSuccess: () => feedback.notify(row.enabled ? 'Key disabled.' : 'Key enabled.'), onError: feedback.fail })}><Typography variant="caption">{row.enabled ? 'Disable' : 'Enable'}</Typography></IconButton><IconButton aria-label="Delete key" color="error" onClick={() => setConfirm({ kind: 'delete', key: row })}><DeleteOutlineRounded fontSize="small" /></IconButton></Stack> : null }];
  if (keys.isLoading || models.isLoading || teams.isLoading) return <LoadingState label="Loading keys" />; if (keys.isError) return <ErrorState error={keys.error} onRetry={() => void keys.refetch()} />; if (!keys.data?.items.length) return <><PageHeader title="Virtual keys" description="Manage budgets, access, and lifecycle for gateway credentials." action={canMutate ? <Button variant="contained" startIcon={<AddRounded />} onClick={() => setCreateOpen(true)}>Create key</Button> : undefined} /><EmptyState title="No virtual keys" description="Create a key to start issuing scoped gateway credentials." /></>;
  return <><PageHeader title="Virtual keys" description="Manage budgets, access, and lifecycle for gateway credentials." action={canMutate ? <Button variant="contained" startIcon={<AddRounded />} onClick={() => setCreateOpen(true)}>Create key</Button> : undefined} /><DataTable rows={keys.data.items} columns={columns} rowCount={keys.data.total} loading={keys.isFetching} /><Stack direction="row" justifyContent="flex-end"><Button disabled={page === 0} onClick={() => setPage((value) => value - 1)}>Previous</Button><Button disabled={(page + 1) * 25 >= keys.data.total} onClick={() => setPage((value) => value + 1)}>Next</Button></Stack><KeyDialog open={createOpen} title="Create virtual key" form={form} setForm={setForm} models={models.data?.items.map((model) => model.name) ?? []} teams={teams.data?.items ?? []} onClose={() => setCreateOpen(false)} onSubmit={submitCreate} submitting={create.isPending} /><EditDialog keyValue={edit} onChange={setEdit} onClose={() => setEdit(null)} onSave={submitEdit} /><ConfirmDialog open={Boolean(confirm)} title={confirm?.kind === 'delete' ? 'Delete virtual key?' : 'Regenerate virtual key?'} description={confirm?.kind === 'delete' ? `Deleting ${confirm?.key.name} permanently removes this credential and its access.` : `Regenerating ${confirm?.key.name} immediately stops the old key from working.`} confirmLabel={confirm?.kind === 'delete' ? 'Delete key' : 'Regenerate'} onClose={() => setConfirm(null)} onConfirm={runConfirm} /><Dialog open={Boolean(plaintext)} onClose={() => setPlaintext(null)}><DialogTitle>Copy your new key now</DialogTitle><DialogContent><Typography color="warning.main" sx={{ mb: 2 }}>This plaintext key will not be shown again. Store it securely before closing.</Typography><Stack direction="row" alignItems="center" spacing={1}><Typography sx={{ wordBreak: 'break-all' }}>{plaintext}</Typography>{plaintext && <CopyButton value={plaintext} label="Copy key" />}</Stack></DialogContent><DialogActions><Button onClick={() => setPlaintext(null)}>Done</Button></DialogActions></Dialog>{feedback.node}</>;
}
function KeyDialog({ open, title, form, setForm, models, teams, onClose, onSubmit, submitting }: { open: boolean; title: string; form: KeyCreateRequest; setForm: (form: KeyCreateRequest) => void; models: string[]; teams: { id: string; name: string }[]; onClose: () => void; onSubmit: () => void; submitting: boolean }) { return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{title}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /><FormControl><InputLabel>Team</InputLabel><Select label="Team" value={form.team_id ?? ''} onChange={(event) => setForm({ ...form, team_id: event.target.value || null })}><MenuItem value="">No team</MenuItem>{teams.map((team) => <MenuItem key={team.id} value={team.id}>{team.name}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Allowed models</InputLabel><Select multiple label="Allowed models" value={form.allowed_models ?? []} onChange={(event) => setForm({ ...form, allowed_models: event.target.value as string[] })}>{models.map((model) => <MenuItem key={model} value={model}>{model}</MenuItem>)}</Select></FormControl><TextField label="Max budget (USD)" type="number" value={form.max_budget_usd ?? ''} onChange={(event) => setForm({ ...form, max_budget_usd: event.target.value ? Number(event.target.value) : null })} /><TextField label="Budget period" value={form.budget_duration ?? 'monthly'} onChange={(event) => setForm({ ...form, budget_duration: event.target.value })} /><Stack direction="row" spacing={2}><TextField fullWidth label="RPM limit" type="number" value={form.rpm_limit ?? ''} onChange={(event) => setForm({ ...form, rpm_limit: event.target.value ? Number(event.target.value) : null })} /><TextField fullWidth label="TPM limit" type="number" value={form.tpm_limit ?? ''} onChange={(event) => setForm({ ...form, tpm_limit: event.target.value ? Number(event.target.value) : null })} /></Stack><TextField label="Expiry" type="datetime-local" InputLabelProps={{ shrink: true }} value={form.expires_at?.slice(0, 16) ?? ''} onChange={(event) => setForm({ ...form, expires_at: event.target.value ? new Date(event.target.value).toISOString() : null })} /></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={onSubmit} disabled={!form.name.trim() || submitting}>Create</Button></DialogActions></Dialog>; }
function EditDialog({ keyValue, onChange, onClose, onSave }: { keyValue: VirtualKey | null; onChange: (value: VirtualKey | null) => void; onClose: () => void; onSave: () => void }) { return <Dialog open={Boolean(keyValue)} onClose={onClose}><DialogTitle>Edit limits</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Typography color="text.secondary">Adjust the limits or disable this key without deleting its audit record.</Typography><TextField label="Max budget (USD)" type="number" value={keyValue?.max_budget_usd ?? ''} onChange={(event) => keyValue && onChange({ ...keyValue, max_budget_usd: event.target.value ? Number(event.target.value) : null })} /><TextField label="RPM limit" type="number" value={keyValue?.rpm_limit ?? ''} onChange={(event) => keyValue && onChange({ ...keyValue, rpm_limit: event.target.value ? Number(event.target.value) : null })} /><TextField label="TPM limit" type="number" value={keyValue?.tpm_limit ?? ''} onChange={(event) => keyValue && onChange({ ...keyValue, tpm_limit: event.target.value ? Number(event.target.value) : null })} /><TextField label="Status" select value={keyValue?.enabled ? 'enabled' : 'disabled'} onChange={(event) => keyValue && onChange({ ...keyValue, enabled: event.target.value === 'enabled' })}><MenuItem value="enabled">Enabled</MenuItem><MenuItem value="disabled">Disabled</MenuItem></TextField></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={onSave}>Save limits</Button></DialogActions></Dialog>; }
