import { Card, CardContent, Chip, Divider, Stack, Typography } from '@mui/material';
import { ErrorState, EmptyState, LoadingState, PageHeader } from '../components/Shared';
import { useAuth } from '../auth/AuthProvider';
import { useSystemInfo } from '../api/hooks/useAdmin';
import { StatusChip } from '../features/admin/AdminPrimitives';
import UserManagement from '../features/admin/UserManagement';
import { useProviderStatus } from '../api/hooks/useUsers';
export default function Settings() { const { user } = useAuth(); const system = useSystemInfo(); if (system.isLoading) return <LoadingState label="Loading system settings" />; if (system.isError) return <ErrorState error={system.error} onRetry={() => void system.refetch()} />; const info = system.data; if (!info) return <EmptyState title="No system information" />; return <><PageHeader title="Settings" description="Review console access and gateway runtime status." /><Stack spacing={3}><Card><CardContent><Typography variant="h3">Admin users</Typography>{user?.role === 'admin' ? <UserManagement currentEmail={user.username} /> : <Typography color="text.secondary" sx={{ mt: 1 }}>Only administrators can manage console users.</Typography>}</CardContent></Card><Card><CardContent><Typography variant="h3">System information</Typography><Stack direction="row" flexWrap="wrap" gap={1.5} sx={{ mt: 2 }}><Metric label="Version" value={info.version} /><Metric label="Environment" value="Gateway runtime" /><Metric label="Uptime" value={formatUptime(info.uptime_seconds)} /><Metric label="Database" value={info.database_connected ? 'Connected' : 'Degraded'} status={!info.database_connected} /><Metric label="Redis" value={info.redis_connected ? 'Connected' : 'Degraded'} status={!info.redis_connected} /></Stack><Divider sx={{ my: 3 }} /><Typography variant="h3">Configured providers</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 1.5 }}>{info.providers.length ? info.providers.map((provider) => <Chip key={provider} label={provider} variant="outlined" />) : <Typography color="text.secondary">No providers reported.</Typography>}</Stack><ProviderCredentials /><Divider sx={{ my: 3 }} /><Typography variant="h3">Optional subsystems</Typography><Stack direction="row" flexWrap="wrap" gap={1} sx={{ mt: 1.5 }}>{Object.entries(info.features).map(([name, active]) => <StatusChip key={name} value={`${name}: ${active ? 'active' : 'inactive'}`} />)}</Stack></CardContent></Card></Stack></>; }
function Metric({ label, value, status = false }: { label: string; value: string; status?: boolean }) { return <Card variant="outlined" sx={{ minWidth: 150, flex: '1 1 150px' }}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h3" color={status ? 'error.main' : undefined} sx={{ mt: 0.5 }}>{value}</Typography></CardContent></Card>; }
function formatUptime(seconds: number): string { const days = Math.floor(seconds / 86400); const hours = Math.floor((seconds % 86400) / 3600); const minutes = Math.floor((seconds % 3600) / 60); return `${days}d ${hours}h ${minutes}m`; }
function ProviderCredentials() { const status = useProviderStatus(); if (status.isLoading) return <LoadingState label="Checking provider credentials" />; if (status.isError) return <ErrorState error={status.error} onRetry={() => void status.refetch()} />; return <Stack spacing={1} sx={{ mt: 2 }}>{(status.data?.items ?? []).map((item) => <Stack key={item.provider} direction="row" spacing={1} alignItems="center"><Typography sx={{ minWidth: 100, fontWeight: 600 }}>{item.provider}</Typography><StatusChip value={item.configured ? 'credentials configured' : 'not configured'} /><StatusChip value={item.reachable ? 'reachable' : 'unreachable'} /></Stack>)}</Stack>; }
